service: aws-node-api-serverless
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  stackName: api-serverless
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:Get*'
        - 'dynamodb:Scan*'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/example-table-${self:provider.stage}

  environment:
    SWAPI_BASE_URL: ${env:SWAPI_BASE_URL}
    DYNAMO_TABLE_NAME: example-table-${self:provider.stage}

functions:
  getStarWarsPlanet:
    handler: src/functions/getStarWarsPlanet.handler
    name: get-star-wars-planet-${self:provider.stage}
    timeout: 10
    events:
      - httpApi:
          path: /api/v1/star-wars/planet/{id}
          method: get
  getStarWarsPerson:
    handler: src/functions/getStarWarsPerson.handler
    name: get-star-wars-person-${self:provider.stage}
    timeout: 10
    events:
      - httpApi:
          path: /api/v1/star-wars/person/{id}
          method: get
  createInsurancePolicy:
    handler: src/functions/createInsurancePolicy.handler
    name: create-insurance-policy-${self:provider.stage}
    timeout: 10
    events:
      - httpApi:
          path: /api/v1/insurance-policy
          method: post
  getAllInsurancePolicies:
    handler: src/functions/getAllInsurancePolicies.handler
    name: get-all-insurance-policies-${self:provider.stage}
    timeout: 10
    events:
      - httpApi:
          path: /api/v1/insurance-policy
          method: get

resources:
  Resources:
    ExampleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: example-table-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-offline
  - serverless-esbuild
