service: aws-node-api-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-offline
  - serverless-esbuild
